name: CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install xorg-dev libglu1-mesa-dev mesa-common-dev mesa-utils xvfb

    - name: Build
      run: |
        cd ..
        bash toucan/SuperBuild.sh Debug

    - name: Tests
      run: |
        cd ..
        cmake --build build-Debug --target test

  macos-12-build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        cd ..
        bash toucan/SuperBuild.sh Debug

    - name: Tests
      run: |
        cd ..
        cmake --build build-Debug --target test

  macos-14-build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        cd ..
        bash toucan/SuperBuild.sh Debug

    - name: Tests
      run: |
        cd ..
        cmake --build build-Debug --target test

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: ilammy/setup-nasm@v1
        
    - name: Build
      shell: cmd
      run: |
        cd ..
        toucan\SuperBuild.bat Debug

    - name: Tests
      run: |
        cd ..
        cmake --build build-Debug --target RUN_TESTS
